#!/usr/bin/env bash
# This script retrieves DNS records for subdomains of a given domain

get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    result=$(dig +short "$subdomain.$domain" A)
    if [[ -n $result ]]; then
        echo "The subdomain $subdomain is a A record and points to $result"
    fi
}

main() {
    local domain=$1
    local subdomain=$2

    if [[ -n $subdomain ]]; then
        get_subdomain_info "$domain" "$subdomain"
    else
        for sub in www lb-01 web-01 web-02; do
            get_subdomain_info "$domain" "$sub"
        done
    fi
}

main "$@"

