#!/usr/bin/env bash
# Fixes Nginx to listen on port 80
apt-get update > /dev/null
apt-get install -y nginx > /dev/null
sed -i 's/^#*listen\s*80;/listen 80;/' /etc/nginx/sites-available/default
service nginx restart > /dev/null
service nginx stop

