#!/bin/bash
for file for file in *.html; do if [ ! -e "../$file" ]; then cp -u "$file" "../"; echo "Copied $file to ../"; elif [ "$file" -nt "../$file" ]; then cp -u "$file" "../"; echo "Copied $file to ../"; fi; done
