#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely, with a 2-second pause between each line,
# and prints "I am invincible!!!" when a SIGTERM signal is received.

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
    echo "To infinity and beyond"
    sleep 2
done
