#!/usr/bin/env bash

# Function to handle SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop to print message with delay
while true; do
    echo "To infinity and beyond"
    sleep 2
done
