#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine

# Extract unique IPv4 addresses from /proc/net/fib_trie
grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' /proc/net/fib_trie | sort -u

